=== ScaredyCat/ADSL2-PCI-Card-Single-Port-ADSL-Modem/opensource/OpenAgent2.0/conf/param.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema from XMLSpy v2005 create://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="TR069">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="trf"/>
				<xs:element ref="lib"/>
				<xs:element ref="wandev"/>
				<xs:element ref="install"/>
				<xs:element ref="manu"/>
				<xs:element ref="oui"/>
				<xs:element ref="class"/>
				<xs:element ref="serial"/>
				<xs:element ref="paramkey"/>
				<xs:element ref="upfig"/>
				<xs:element ref="uplog"/>
				<xs:element ref="downsys"/>
				<xs:element ref="downkil"/>
				<xs:element ref="downpar"/>
				<xs:element ref="taskwst"/>
				<xs:element ref="taskweb"/>
				<xs:element ref="taskfla"/>
				<xs:element ref="taskreb"/>
				<xs:element ref="trcmd"/>
				<xs:element ref="ca_cert"/>
				<xs:element ref="cl_cert"/>
				<xs:element ref="cl_key"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="trf">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="obj"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lib">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[/._0-9a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="wandev">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="install">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="manu">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="oui">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="class">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="serial">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="paramkey">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="upfig">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="uplog">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="downsys">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="downkil">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="downpar">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="taskwst">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="taskweb">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="taskfla">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="taskreb">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="trcmd">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ca_cert">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[/._0-9a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="cl_cert">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
						<xs:pattern value="[/._0-9a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="cl_key">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="49"/>
                        <xs:pattern value="[/._0-9a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="obj">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="obj" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="27"/>
						<xs:pattern value="[0-9a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="rw" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="0"/>
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="max" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="2"/>
					    <xs:pattern value="[0-9]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="obj_dev_func" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="29"/>
						<xs:pattern value="[0-9_a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="obj_instance_func" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="29"/>
						<xs:pattern value="[0-9_a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="param">
		<xs:complexType mixed="true">
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="35"/>
						<xs:pattern value="[0-9a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
                        <xs:attribute name="noti" use="optional">
                                <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                                <xs:enumeration value="0"/>
                                                <xs:enumeration value="1"/>
                                                <xs:enumeration value="2"/>
                                        </xs:restriction>
                                </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="noti_rw" use="optional">
                                <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                                <xs:enumeration value="0"/>
                                                <xs:enumeration value="2"/>
                                        </xs:restriction>
                                </xs:simpleType>
                        </xs:attribute>
			<xs:attribute name="rw" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="0"/>
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="B"/>
						<xs:enumeration value="b"/>
						<xs:enumeration value="d"/>
						<xs:enumeration value="i"/>
						<xs:enumeration value="s"/>
						<xs:enumeration value="u"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="dev_func" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					    <xs:maxLength value="59"/>
						<xs:pattern value="[0-9_a-zA-Z]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ScaredyCat/ADSL2-PCI-Card-Single-Port-ADSL-Modem/opensource/OpenAgent2.0/conf/param.xml
<!--Param.xml for Agent-->
<?xml version="1.0" encoding="UTF-8"?>
<TR069 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/root/param.xsd">
<trf>
    <obj name="InternetGatewayDevice" rw="0">
        <param name="LANDeviceNumberOfEntries" rw="0" type="u" noti="1" dev_func="dev_landev_num">
        </param>
	    <param name="WANDeviceNumberOfEntries" rw="0" type="u" dev_func="dev_wandev_num">
        </param>
        <obj name="DeviceInfo" rw="0">
           <param name="Manufacturer" rw="0" type="s" dev_func="dev_Manufacturer">      
	          </param>
	        <param name="ManufacturerOUI" rw="0" type="s" dev_func="dev_ManufacturerOUI">
	        </param>
	        <param name="ModelName" rw="0" type="s" dev_func="dev_ModelName">
            </param>
			<param name="Description" rw="0" type="s" dev_func="dev_Description">
			</param>
			<param name="ProductClass" rw="0" type="s" dev_func="dev_ProductClass">
			</param>
			<param name="SerialNumber" rw="0" type="s" dev_func="dev_SerialNumber">
			</param>
			<param name="HardwareVersion" rw="0" type="s" dev_func="dev_HardwareVersion">
			 </param>
			<param name="SoftwareVersion" rw="0" type="s" noti="2" noti_rw="0" dev_func="dev_SoftwareVersion">
			</param>
			<param name="ModemFirmwareVersion" rw="0" type="s" dev_func="dev_Modem_Ver">
			</param>
			<param name="EnabledOptions" rw="0" type="s" dev_func="dev_Enable_Opt">
			</param>
			<param name="AdditionalHardwareVersion" rw="0" type="s" dev_func="dev_Additional_Hard_Ver">
			</param>
			<param name="AdditionalSoftwareVersion" rw="0" type="s" dev_func="dev_Additional_Soft_Ver">
			</param>
			<param name="SpecVersion" rw="0" type="s" dev_func="dev_SpecVersion">
			</param>
			<param name="ProvisioningCode" rw="0" type="s" noti="2" noti_rw="0" dev_func="dev_ProvisioningCode">
			</param>
			<param name="UpTime" rw="0" type="u" dev_func="dev_UpTime">
			</param>
			<param name="FirstUseDate" rw="0" type="d" dev_func="dev_FirstUserDate">
			</param>
			<param name="DeviceLog" rw="0" type="s" dev_func="dev_DeviceLog">
			</param>
			<param name="VendorConfigFileNumberOfEntries" rw="0" type="s" dev_func="dev_Vendor_CFile_Num">
			</param>
	        <obj name="VendorConfigFile" rw="0">
     	        <obj name="1" rw="0">
			        <param name="Name" rw="0" type="s" dev_func="dev_VendorFile_name">
				    </param>
					<param name="Version" rw="0" type="s" dev_func="dev_VendorFile_version">
					</param>
					<param name="Date" rw="0" type="d" dev_func="dev_VendorFile_date">
				    </param>
					<param name="Description" rw="0" type="s" dev_func="dev_VendorFile_description">
				    </param>
			    </obj>
		    </obj>
	    </obj>
		<obj name="DeviceConfig" rw="0">
		    <param name="PersistentData" rw="2" type="s" dev_func="dev_PersistentData">
			</param>
			<param name="ConfigFile" rw="2" type="s" dev_func="dev_ConfigFile">
			</param>
		</obj>
		<obj name="ManagementServer" rw="0">
			<param name="URL" rw="2" type="s" dev_func="dev_ManageServer_URL">
			</param>
			<param name="Username" rw="1" type="s" dev_func="dev_ManageServer_Username">
			</param>
			<param name="Password" rw="2" type="s" dev_func="dev_ManageServer_Password">
			</param>
			<param name="PeriodicInformEnable" rw="2" type="b" dev_func="dev_ManageServer_PeriodicInformEnable">
			</param>
			<param name="PeriodicInformInterval" rw="2" type="u" dev_func="dev_ManageServer_PeriodicInformInterval">
			</param>
			<param name="PeriodicInformTime" rw="2" type="d" dev_func="dev_ManageServer_PeriodicInformTime">
			</param>
			<param name="ParameterKey" rw="0" type="s" dev_func="dev_ManageServer_ParameterKey">
			</param>
			<param name="ConnectionRequestURL" rw="0" type="s" noti="2" noti_rw="0" dev_func="dev_ManageServer_ConnectionRequestURL">
			</param>
			<param name="ConnectionRequestUsername" rw="2" type="s" dev_func="dev_ManageServer_ConnectionRequestUsername">
			</param>
			<param name="ConnectionRequestPassword" rw="1" type="s" dev_func="dev_ManageServer_ConnectionRequestPassword">
			</param>
			<param name="UpgradesManaged" rw="2" type="b" dev_func="dev_ManageServer_UpgradesManaged">
			</param>
			<param name="KickURL" rw="0" type="s" dev_func="dev_ManageServer_KickURL">
			</param>
			<param name="DownloadProgressURL" rw="0" type="s" dev_func="dev_ManageServer_DownloadProgressURL">
			</param>
		</obj>
		<obj name="Time" rw="0">
			<param name="NTPServer1" rw="2" type="s" dev_func="dev_Time_NTPServer1">
			</param>
			<param name="NTPServer2" rw="2" type="s" dev_func="dev_Time_NTPServer2">
			</param>
			<param name="NTPServer3" rw="2" type="s" dev_func="dev_Time_NTPServer3">
			</param>
			<param name="NTPServer4" rw="2" type="s" dev_func="dev_Time_NTPServer4">
			</param>
			<param name="NTPServer5" rw="2" type="s" dev_func="dev_Time_NTPServer5">
			</param>
			<param name="CurrentLocalTime" rw="0" type="d" dev_func="dev_Time_CurrentLocalTime">
			</param>
			<param name="LocalTimeZone" rw="2" type="s" dev_func="dev_Time_LocalTimeZone">
			</param>
			<param name="LocalTimeZoneName" rw="2" type="s" dev_func="dev_Time_LocalTimeZoneName">
			</param>
			<param name="DaylightSavingsUsed" rw="2" type="b" dev_func="dev_Time_DaylightSavingUsed">
			</param>
			<param name="DaylightSavingsStart" rw="2" type="d" dev_func="dev_Time_DaylightSavingStart">
			</param>
			<param name="DaylightSavingsEnd" rw="2" type="d" dev_func="dev_Time_DaylightSavingEnd">
			</param>
		</obj>	
		<obj name="UserInterface" rw="0">
			<param name="PasswordRequired" rw="2" type="b" dev_func="dev_UI_PasswordRequired">
			</param>
			<param name="PasswordUserSelectable" rw="2" type="b" dev_func="dev_UI_PasswordUserSelectable">
			</param>
			<param name="UpgradeAvailable" rw="2" type="b" dev_func="dev_UI_UpgradeAvailable">
			</param>
			<param name="WarrantyDate" rw="2" type="d" dev_func="dev_UI_WarrantyDate">
			</param>
			<param name="ISPName" rw="2" type="s" dev_func="dev_UI_ISPName">
			</param>
			<param name="ISPHelpDesk" rw="2" type="s" dev_func="dev_UI_ISPHelpDesk">
			</param>
			<param name="ISPHomePage" rw="2" type="s" dev_func="dev_UI_ISPHomePage">
			</param>
			<param name="ISPHelpPage" rw="2" type="s" dev_func="dev_UI_ISPHelpPage">
			</param>
			<param name="ISPLogo" rw="2" type="B" dev_func="dev_UI_ISPLogo">
			</param>
			<param name="ISPLogoSize" rw="2" type="u" dev_func="dev_UI_ISPLogoSize">
			</param>
			<param name="ISPMailServer" rw="2" type="s" dev_func="dev_UI_ISPMailServer">
			</param>
			<param name="ISPNewsServer" rw="2" type="s" dev_func="dev_UI_ISPNewsServer">
			</param>
			<param name="TextColor" rw="2" type="s" dev_func="dev_UI_TextColor">
			</param>
			<param name="BackgroundColor" rw="2" type="s" dev_func="dev_UI_BackgroundColor">
			</param>
			<param name="ButtonColor" rw="2" type="s" dev_func="dev_UI_ButtonColor">
			</param>
			<param name="ButtonTextColor" rw="2" type="s" dev_func="dev_UI_ButtonTextColor">
			</param>
			<param name="AutoUpdateServer" rw="2" type="s" dev_func="dev_UI_AutoUpdateServer">
			</param>
			<param name="UserUpdateServer" rw="2" type="s" dev_func="dev_UI_UserUpdateServer">
			</param>
			<param name="ExampleLogin" rw="2" type="s" dev_func="dev_UI_ExampleLogin">
			</param>
			<param name="ExamplePassword" rw="2" type="s" dev_func="dev_UI_ExamplePassword">
			</param>
		</obj>
		<obj name="Layer3Forwarding" rw="0">
			<param name="DefaultConnectionService" rw="2" type="s" dev_func="dev_Layer3_DefaultConnectionService">
			</param>
			<param name="ForwardNumberOfEntries" rw="0" type="u" dev_func="dev_Layer3_ForwardNumberOfEntries">
			</param>
			<obj name="Forwarding" rw="2" max="9" obj_dev_func="dev_obj_forward" obj_instance_func="get_forwarding_instance">
				<obj name="0" rw="2">
					<param name="Enable" rw="2" type="b" dev_func="dev_Forwarding_Enable">
			   </param>
					<param name="Status" rw="0" type="s" dev_func="dev_Forwarding_Status">
			  </param>
					<param name="Type" rw="2" type="s" dev_func="dev_Forwarding_Type">
			        </param>
					<param name="DestIPAddress" rw="2" type="s" dev_func="dev_Forwarding_DestIPAddress">
			        </param>
					<param name="DestSubnetMask" rw="2" type="s" dev_func="dev_Forwarding_DestSubnetMask">
			        </param>
					<param name="SourceIPAddress" rw="2" type="s" dev_func="dev_Forwarding_SourceIPAddress">
			        </param>
					<param name="SourceSubnetMask" rw="2" type="s" dev_func="dev_Forwarding_SourceSubnetMask">
			        </param>
					<param name="GatewayIPAddress" rw="2" type="s" dev_func="dev_Forwarding_GatewayIPAddress">
			        </param>
					<param name="Interface" rw="2" type="s" dev_func="dev_Forwarding_Interface">
			        </param>
					<param name="ForwardingMetric" rw="2" type="i" dev_func="dev_Forwarding_ForwardingMetric">
			        </param>
					<param name="MTU" rw="2" type="u" dev_func="dev_Forwarding_MTU">
			        </param>
				</obj>
			</obj>
		</obj>
     	<obj name="LANConfigSecurity" rw="0">
			<param name="ConfigPassword" rw="1" type="s" dev_func="dev_LAN_ConfigPassword">
			</param>
		</obj>
		<obj name="IPPingDiagnostics" rw="0">
			<param name="DiagnosticsState" rw="2" type="s" dev_func="dev_IPPing_DiagnosticsState">
			</param>
			<param name="Interface" rw="2" type="s" dev_func="dev_IPPing_Interface">
			</param>
			<param name="Host" rw="2" type="s" dev_func="dev_IPPing_Host">
			</param>
			<param name="NumberOfRepetitions" rw="2" type="u" dev_func="dev_IPPing_NumberOfRepetitions">
			</param>
			<param name="Timeout" rw="2" type="u" dev_func="dev_IPPing_Timeout">
			</param>
			<param name="DataBlockSize" rw="2" type="u" dev_func="dev_IPPing_DataBlockSize">
			</param>
			<param name="DSCP" rw="2" type="u" dev_func="dev_IPPing_DSCP">
			</param>
			<param name="SuccessCount" rw="0" type="u" dev_func="dev_IPPing_SuccessCount">
			</param>
			<param name="FailureCount" rw="0" type="u" dev_func="dev_IPPing_FailureCount">
			</param>
